version: 2
jobs:
  build:
    environment:
      DOCKER_VER: "17.11.0-ce"
      DOCKER_TRACK: "edge"  # edge or stable
    docker:
      - image: node:8.6.0
      - image: sammlerio/rabbitmq:0.1.3
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - add_ssh_keys
      - run:
          name: Install npm
          command: npm install --silent
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Install Docker client
          command: |
            echo "Install docker client for version: $DOCKER_VER"
            curl -L -o /tmp/docker-$DOCKER_VER.tgz https://download.docker.com/linux/static/${DOCKER_TRACK:-stable}/x86_64/docker-$DOCKER_VER.tgz
            tar -xz -C /tmp -f /tmp/docker-${DOCKER_VER}.tgz
            mv /tmp/docker/* /usr/bin
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm run test
      - run:
          name: Coverage
          command: |
            npm run test:unit:coverage
            bash <(curl -s https://codecov.io/bash)
