version: 2
jobs:
  build:
    docker:
      - image: node:8.6.0
    working_directory: ~/app
    environment:
      DOCKER_VER: "17.07.0-ce"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - add_ssh_keys
      - setup_remote_docker:
          version: $DOCKER_VER
      - run:
          name: Install Docker client
          command: |
            curl -L -o /tmp/docker-$DOCKER_VER.tgz https://download.docker.com/linux/static/${TRACK:-stable}/x86_64/docker-$DOCKER_VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VER.tgz
            mv /tmp/docker/* /usr/bin
